### ISSUE TITLE
display errors on 68k with ECS Denise

### ISSUE THREAD

**Issue by wepl** [aros-development-team/AROS#639]
**Describe the bug**
When using WinUAE or vAmiga the display is corrupt/rolling when using ECS Denise.

**To Reproduce**
WinUAE:
I used Quickstart A1200, but other should work too
Set Hardware - Chipset - Chipset - ECS Denise
insert any boot disk (HD or FD) without any content
boot, so that initial CLI is displayed
-> gfx distorted
vAmiga:
select agnus_revision=ECS_2MB

**Expected behaviour**
Working as with OCS or AGA.
Problem vAmiga only supports OCS/ECS and OCS is restricted to 512K Chip Memory

**Screenshots**
![image](https://github.com/aros-development-team/AROS/assets/3184445/b20d332a-bd4b-41d1-903e-de92c66a577e)

**Architecture**
WinUAE 5.2.0
vAmigaWeb core 2.6.0
 
**CPU**
 - m68k

**Version**
Daily Snapshot 20240313

**Comment by thatguywiththekids** [comment]
Setting ECS for specific chips only does not sound like a config AROS is expected to support. Is there any problem with using a full ECS setup?

**Comment by deadwood2** [comment]
Comment from Toni Wilen on this issue: "If this is ECS Denise with OCS Agnus: not even official KS support this combination (for example KS 3.1 has broken mouse cursor and a slightly wonky display position using this config)"

**Comment by wepl** [comment]
It works fine with Kickstart 3.1.
It also worked in some older releases of AROS (don't have exact version ATM).
ECS Agnus + ECS Denise has the same problem.
It's the only way to get more than 512K chip on vAmiga.

**Comment by thatguywiththekids** [comment]
The setting "Full ECS" in WinUAE works fine with AROS here, at least in the test case this issue concerns. I tested both A500+ and A3000 with AROS roms. I can however say that OCS looks terrible.

**Comment by wepl** [comment]
You can check here https://whdload.de/ctros/CopyrightDestroyersInc_3DT.html
Enter Settings and select agnus revision=ECS_1MB or ECS_2MB and wait for reboot.
You may also select denise revision=ECS, it makes no difference.
If you change to CBM kickstart (kick40063.a600) it works.

**Comment by thatguywiththekids** [comment]
I pushed an OCS fix to the deadwood fork. I'll look into making a pull request here too.

**Comment by thatguywiththekids** [comment]
https://github.com/aros-development-team/AROS/pull/670

**Comment by wepl** [comment]
Thanks a lot, working fine now!

**Comment by mithrendal** [comment]
this rolling/corruption bug is still there when 
 
+ using WinUAE 5.31 and the option `ECS Denise`

+ vAmiga 4 with option `ECS Agnus` + `ECS Denise`


The only way to get latest AROS behave correctly with 2MB chip ram is

+ in WinUAE: `FULL ECS `

+ in vAmiga: `ECS Agnus` + `OCS Denise` 


web version of vAmiga  https://vamigaweb.github.io

**Comment by thatguywiththekids** [comment]
OCS Agnus + ECS Denise is not a supported option. WinUAE likely just has the option for completeness.

If vAmiga has an issue that WinUAE does not have, it points to a problem with the vAmiga emulator itself.

Is there any remaining issue after considering the above?

**Comment by mithrendal** [comment]
> it points to a problem with the vAmiga emulator itself.

vAmigaWeb had a glitch in the ECS Agnus implementation.

see here for in depth analysis 

https://github.com/dirkwhoffmann/vAmiga/issues/899




it is already fixed in [vAmigaWeb 4.1](https://vamigaweb.github.io/) which ships also the February build of the aros roms

<img width="1004" alt="Image" src="https://github.com/user-attachments/assets/a251c0e5-6a8f-48c0-aeb1-14a9860df986" />



@thatguywiththekids  this link is broken, responds with 404 --->  http://www.aros.org/nightly1.php
